### ISSUE TITLE
backup download --filter  does not work

### ISSUE THREAD

**Issue by jdsn** [crowbar/crowbar-client#57]
```
crowbarctl backup  list --filter mybackup
/usr/lib64/ruby/gems/2.1.0/gems/crowbar-client-2.3.0/lib/crowbar/client/filter/hash.rb:24:in `block (2 levels) in process': undefined method `include?' for 1:Fixnum (NoMethodError)
        from /usr/lib64/ruby/gems/2.1.0/gems/crowbar-client-2.3.0/lib/crowbar/client/filter/hash.rb:23:in `map'
        from /usr/lib64/ruby/gems/2.1.0/gems/crowbar-client-2.3.0/lib/crowbar/client/filter/hash.rb:23:in `block in process'
        from /usr/lib64/ruby/gems/2.1.0/gems/crowbar-client-2.3.0/lib/crowbar/client/filter/hash.rb:22:in `select'
        from /usr/lib64/ruby/gems/2.1.0/gems/crowbar-client-2.3.0/lib/crowbar/client/filter/hash.rb:22:in `process'
        from /usr/lib64/ruby/gems/2.1.0/gems/crowbar-client-2.3.0/lib/crowbar/client/filter/base.rb:29:in `result'
        from /usr/lib64/ruby/gems/2.1.0/gems/crowbar-client-2.3.0/lib/crowbar/client/command/backup/list.rb:41:in `block in execute'
        from /usr/lib64/ruby/gems/2.1.0/gems/crowbar-client-2.3.0/lib/crowbar/client/request/base.rb:75:in `process'
        from /usr/lib64/ruby/gems/2.1.0/gems/crowbar-client-2.3.0/lib/crowbar/client/command/backup/list.rb:32:in `execute'
        from /usr/lib64/ruby/gems/2.1.0/gems/crowbar-client-2.3.0/lib/crowbar/client/app/backup.rb:71:in `list'
        from /usr/lib64/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /usr/lib64/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /usr/lib64/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /usr/lib64/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
        from /usr/lib64/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:235:in `block in subcommand'
        from /usr/lib64/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /usr/lib64/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /usr/lib64/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /usr/lib64/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /usr/lib64/ruby/gems/2.1.0/gems/crowbar-client-2.3.0/lib/crowbar/client/util/runner.rb:47:in `execute!'
        from /usr/lib64/ruby/gems/2.1.0/gems/crowbar-client-2.3.0/bin/crowbarctl:34:in `<top (required)>'
        from /usr/bin/crowbarctl:23:in `load'
        from /usr/bin/crowbarctl:23:in `<main>'
```

**Comment by tboerger** [comment]
Fixed with https://github.com/crowbar/crowbar-client/pull/66
