### ISSUE TITLE
backup download is broken when using name (instead of ID)

### ISSUE THREAD

**Issue by jdsn** [crowbar/crowbar-client#59]
```
crowbarctl backup download mybackup
/usr/lib64/ruby/gems/2.1.0/gems/crowbar-client-2.3.0/lib/crowbar/client/command/backup/download.rb:61:in `path': undefined method `[]' for nil:NilClass (NoMethodError)
        from /usr/lib64/ruby/gems/2.1.0/gems/crowbar-client-2.3.0/lib/crowbar/client/command/backup/download.rb:37:in `block in execute'
        from /usr/lib64/ruby/gems/2.1.0/gems/crowbar-client-2.3.0/lib/crowbar/client/request/base.rb:75:in `process'
        from /usr/lib64/ruby/gems/2.1.0/gems/crowbar-client-2.3.0/lib/crowbar/client/command/backup/download.rb:31:in `execute'
        from /usr/lib64/ruby/gems/2.1.0/gems/crowbar-client-2.3.0/lib/crowbar/client/app/backup.rb:105:in `download'
        from /usr/lib64/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /usr/lib64/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /usr/lib64/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /usr/lib64/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
        from /usr/lib64/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:235:in `block in subcommand'
        from /usr/lib64/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /usr/lib64/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /usr/lib64/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /usr/lib64/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /usr/lib64/ruby/gems/2.1.0/gems/crowbar-client-2.3.0/lib/crowbar/client/util/runner.rb:47:in `execute!'
        from /usr/lib64/ruby/gems/2.1.0/gems/crowbar-client-2.3.0/bin/crowbarctl:34:in `<top (required)>'
        from /usr/bin/crowbarctl:23:in `load'
        from /usr/bin/crowbarctl:23:in `<main>'
```

**Comment by tboerger** [comment]
Fixed with https://github.com/crowbar/crowbar-client/pull/66
