### ISSUE TITLE
backup upload FILE not working

### ISSUE THREAD

**Issue by jdsn** [crowbar/crowbar-client#60]
`# crowbarctl backup --debug upload mybackup2.tar.gz`

```
I, [2016-01-22T13:05:46.126892 #18453]  INFO -- : Started POST "/utils/backups/upload" for 127.0.0.1 at 2016-01-22 13:05:46 +0000
I, [2016-01-22T13:05:46.128356 #18453]  INFO -- : Processing by BackupsController#upload as JSON
I, [2016-01-22T13:05:46.128466 #18453]  INFO -- :   Parameters: {"file"=>#<ActionDispatch::Http::UploadedFile:0x00000005169748 @tempfile=#<Tempfile:/tmp/RackMultipart20160122-18453-1khx4rb.gz>, @original_filename="mybackup2.tar.gz", @content_type="application/octet-stream", @headers="Content-Disposition: form-data; name=\"file\"; filename=\"mybackup2.tar.gz\"\r\nContent-Length: 127400\r\nContent-Type: application/octet-stream\r\nContent-Transfer-Encoding: binary\r\n">}
I, [2016-01-22T13:05:46.129091 #18453]  INFO -- : Completed 400 Bad Request in 1ms (ActiveRecord: 0.0ms)
F, [2016-01-22T13:05:46.130174 #18453] FATAL -- : 
ActionController::ParameterMissing (param is missing or the value is empty: backup):
  app/controllers/backups_controller.rb:171:in `backup_upload_params'
  app/controllers/backups_controller.rb:113:in `upload'
```

**Comment by tboerger** [comment]
@rsalevsky this error still happens, have you checked your API fix?

**Comment by rsalevsky** [comment]
Issue is fixed.
