### ISSUE TITLE
backup restore runs into timeout

### ISSUE THREAD

**Issue by MaximilianMeister** [crowbar/crowbar-client#73]
```
root@crowbar:~ # crowbarctl backup restore test
Usage of this command is dangerous as it overwrites the
current state of the server and the proposals. Are you
sure you want to proceed?
 [yes, no] yes
/usr/lib64/ruby/2.1.0/net/protocol.rb:158:in `rescue in rbuf_fill': Net::ReadTimeout (Net::ReadTimeout)
        from /usr/lib64/ruby/2.1.0/net/protocol.rb:152:in `rbuf_fill'
        from /usr/lib64/ruby/2.1.0/net/protocol.rb:134:in `readuntil'
        from /usr/lib64/ruby/2.1.0/net/protocol.rb:144:in `readline'
        from /usr/lib64/ruby/2.1.0/net/http/response.rb:39:in `read_status_line'
        from /usr/lib64/ruby/2.1.0/net/http/response.rb:28:in `read_new'
        from /usr/lib64/ruby/2.1.0/net/http.rb:1408:in `block in transport_request'
        from /usr/lib64/ruby/2.1.0/net/http.rb:1405:in `catch'
        from /usr/lib64/ruby/2.1.0/net/http.rb:1405:in `transport_request'
        from /usr/lib64/ruby/2.1.0/net/http.rb:1378:in `request'
        from /usr/lib64/ruby/2.1.0/net/http.rb:1371:in `block in request'
        from /usr/lib64/ruby/2.1.0/net/http.rb:853:in `start'
        from /usr/lib64/ruby/2.1.0/net/http.rb:1369:in `request'
        from /usr/lib64/ruby/gems/2.1.0/gems/httparty-0.13.7/lib/httparty/request.rb:117:in `perform'
        from /usr/lib64/ruby/gems/2.1.0/gems/httparty-0.13.7/lib/httparty.rb:545:in `perform_request'
        from /usr/lib64/ruby/gems/2.1.0/gems/httmultiparty-0.3.16/lib/httmultiparty.rb:124:in `post'
        from /usr/lib64/ruby/gems/2.1.0/gems/crowbar-client-2.4.1/lib/crowbar/client/request/party.rb:53:in `method_missing'
        from /usr/lib64/ruby/gems/2.1.0/gems/crowbar-client-2.4.1/lib/crowbar/client/request/base.rb:53:in `process'
        from /usr/lib64/ruby/gems/2.1.0/gems/crowbar-client-2.4.1/lib/crowbar/client/command/backup/restore.rb:29:in `execute'
        from /usr/lib64/ruby/gems/2.1.0/gems/crowbar-client-2.4.1/lib/crowbar/client/app/backup.rb:104:in `restore'
        from /usr/lib64/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /usr/lib64/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /usr/lib64/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /usr/lib64/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
        from /usr/lib64/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:235:in `block in subcommand'
        from /usr/lib64/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /usr/lib64/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /usr/lib64/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /usr/lib64/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /usr/lib64/ruby/gems/2.1.0/gems/crowbar-client-2.4.1/lib/crowbar/client/util/runner.rb:47:in `execute!'
        from /usr/lib64/ruby/gems/2.1.0/gems/crowbar-client-2.4.1/bin/crowbarctl:34:in `<top (required)>'
        from /usr/bin/crowbarctl:23:in `load'
        from /usr/bin/crowbarctl:23:in `<main>'

```

**Comment by tboerger** [comment]
Shame on you if it's still done in realtime... I already suggested to just trigger the restore instead of waiting for the result.

**Comment by MaximilianMeister** [comment]
I created this issue to track the problem, to not forget about it because there is currently a lot of other things to work on. if you would have followed the PR's in core about the restore, you would have noticed that there were changes that caused this issue.
but this is nothing to be ashamed of either, so don't worry ;-)

**Comment by tboerger** [comment]
:+1:
